### ISSUE TITLE
Bulk download of student submissions not working (Chrome, Safari)

### ISSUE THREAD

**Issue by jefrench** [mitodl/edx-sga#296] opened 2021-01-19 19:35 UTC
Attempting to bulk download all student submissions is no longer working. 
![Screen Shot 2021-01-19 at 2 33 26 PM](https://user-images.githubusercontent.com/10065684/105083831-7bc98a80-5a63-11eb-8699-2633a43c5751.png)
![Screen Shot 2021-01-19 at 2 33 36 PM](https://user-images.githubusercontent.com/10065684/105083843-7f5d1180-5a63-11eb-81d0-6d58fbcd3f97.png)
Clicking on the download all submissions button after it has created the zip file (supposedly) simply returns to the "Started preparing student submissions zip file ... " message.

**Comment by pdpinch** [comment] 2021-01-23 01:32
We can reproduce this reliably on our Residential MITx deployment ([ZenDesk #88086](https://odl.zendesk.com/agent/tickets/88086)), and on edx.org ([ZenDesk #58681](https://odl.zendesk.com/agent/tickets/58681)), but only for certain courses. It's not strictly related to the number of students, but it may be related to the size of the zip file. 

It's difficult to debug because there aren't obvious error messages. I'm not sure why we don't leverage the existing Instructor Tasks infrastructure, which places large download files in the Data Downloads tab of the instructor dashboard.

**Comment by HamzaIbnFarooq** [comment] 2021-01-26 10:37
@pdpinch the provided zendesk links are not accessible can you please allow the access?

**Comment by pdpinch** [comment] 2021-03-13 16:10
This was fixed in the 0.16.0 release, which has been deployed to edx.org and to MITx Residential.

**Closed by pdpinch** 2021-03-13 16:10 UTC
