### ISSUE TITLE
No way to download grades if `pollSubmissionDownload` was used

### ISSUE THREAD

**Issue by OmarIthawi** [mitodl/edx-sga#329] opened 2022-09-27 12:02 UTC
When the zip file is large enough to require polling, there's no way to download it. The zip file would be downloadable but there's no UI do so.

### Background
edX SGA XBlock download works in two modes:

 - Download small files immediately after `prepareDownloadSubmissionsUrl` is used, which is the most common case. Works.
 - Download big files after `pollSubmissionDownload` is used which is rare but exists. Implemented but has a bug.

### Steps to Reproduce
The steps to reproduce in LMS are un-reliable unless maybe 100mb of assignments is used. So, I'll be assuming development access:

 - Prepare a course with SGA XBlock that has submissions
 - Edit the sga.py to make `prepareDownloadSubmissionsUrl` return `downloadable=False` to simulate a longer Zip compression process: 
 ```py
  def prepare_download_submissions
      #....
      return Response(json_body={
                  "downloadable":   False,# zip_file_ready
              })
 ```
 - Click on the "Download All Submissions" button in LMS

### Expected results
 a. `window.location = downloadSubmissionsUrl;` is run to force download
 b. OR, A download button would show up

Both are fine

### Actual results

 - `Student submission file ready for download` is shown via:
    https://github.com/mitodl/edx-sga/blob/e4e427b92dd2fbccd3eecb3128e7865425f14ee6/edx_sga/static/js/src/edx_sga.js#L383-L388
- No way to download the file

### Proposed quick fix (may be unreliable due to browser security)

```diff
# edx_sga.js
 function pollSubmissionDownload() {
   pollUntilSuccess(downloadSubmissionsStatusUrl, checkResponse, 10000, 100).then(function() {
     $(element).find('#download-init-button').removeClass("disabled");
     $(element).find('.task-message')
       .show()
       .html(gettext("Student submission file ready for download"))
       .removeClass("preparing-msg")
       .addClass("ready-msg");
+      window.location = downloadSubmissionsUrl;
   }).fail(function() {
```

### Proposed fix (reliable but needs extra testing)
When `pollUntilSuccess` is finished, show a button for download `<a href="{{ downloadSubmissionsUrl }}" target="_blank">...` however this button should be hidden during processing or after a failed prep. Therefore, it needs to be tested well manually.

**Comment by pdpinch** [comment] 2022-09-27 12:08
Thanks @OmarIthawi -- I'm not sure I understand the problem. Are you saying that when the zip file is large enough to require polling, you can't download it?

**Comment by OmarIthawi** [comment] 2022-09-27 12:13
Yes @pdpinch, that's the issue.

**Comment by pdpinch** [comment] 2022-09-28 15:13
Can you confirm which version of SGA you are using (and/or which release of open edX) ?

**Comment by OmarIthawi** [comment] 2022-09-29 08:57
> Can you confirm which version of SGA you are using (and/or which release of open edX) ?

We're currently using `edx-sga==0.11.0` on Juniper.

**Comment by Anas12091101** [comment] 2024-08-22 17:17
I tried to reproduce this issue on the latest edx-sga version 0.25.0. I was able to download the zip files that require polling. After analyzing the code, I observed that for the zip files which require polling, the `Download All Submissions` button needs to be clicked twice. The first click starts the polling process, and when the polling finishes, the button needs to be clicked again to download the file. I believe the reason the file is not downloadable in this issue is due to the hardcoding of:
```
def prepare_download_submissions
     #....
     return Response(json_body={
                 "downloadable": False,  # zip_file_ready
             })
```
This will always return `False`, despite the fact that the polling is completed and the file is ready to download.

Thanks @arslanashraf7 for helping me in analyzing the code
@pdpinch, we can close this issue

**Closed** 2024-09-03 12:45 UTC
Labels: project:open-edx
