### ISSUE TITLE
Studio Error when duplicating a component or a section

### ISSUE THREAD

**Issue by duraiganesh0** [mitodl/edx-sga#306] opened 2021-08-31 20:12 UTC
On ironwood you can reproduce this bug:

1. In Studio create block with sga (in any course)
2. Then go to the course structure page (in studio)
3. Then try to duplicate this block by pushing button "Copy" on the block
4. Getting error

Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 270, in course_handler
    return course_index(request, CourseKey.from_string(course_key_string))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 657, in course_index
    ) if current_action else None,
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 1016, in bulk_operations
    yield
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/__init__.py", line 192, in bulk_operations
    self._end_bulk_operation(course_id, emit_signals, ignore_case)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/__init__.py", line 286, in _end_bulk_operation
    dirty = self._end_outermost_bulk_operation(bulk_ops_record, structure_key)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 254, in _end_outermost_bulk_operation
    self.db_connection.insert_structure(bulk_write_record.structures[_id], bulk_write_record.course_key)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py", line 436, in insert_structure
    self.structures.insert(structure_to_mongo(structure, course_context))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mongodb_proxy.py", line 115, in __call__
    return self.proxied_object(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/collection.py", line 540, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: u'Staff Graded Assignment'

**Comment by pdpinch** [comment] 2021-08-31 20:14
Is this a duplicate of #252?

**Comment by duraiganesh0** [comment] 2021-09-07 03:25
@pdpinch version 0.9.0 is also throwing the same error.

**Comment by asadiqbal08** [comment] 2022-01-04 17:36
@duraiganesh0 Can you confirm is this bug still valid to look over as I am able to add duplicates of SGA xblock without noticing any error. Please let me know if specific needs to test again. 

<img width="996" alt="Screenshot 2022-01-04 at 10 35 53 PM" src="https://user-images.githubusercontent.com/7334669/148100329-1820093d-2bd9-4b28-bbc3-dd8ca54edd79.png">

cc: @pdpinch

**Comment by asadiqbal08** [comment] 2022-01-19 09:36
Should I consider to close this ticket ? @pdpinch

**Comment by pdpinch** [comment] 2022-01-19 13:49
If you can't replicate this in the current release, I think it's OK to close.

**Closed by pdpinch** 2022-01-19 13:49 UTC
